# Generated by Django 6.0.7 on 2026-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('surface', models.FloatField()),
                ('type_sol', models.CharField(max_length=50)),
                ('reserve_max', models.FloatField()),
                ('reserve_actuelle', models.FloatField()),
                ('seuil_minimum', models.FloatField()),
                ('localisation', models.CharField(max_length=100)),
            ],
        ),
    ]
