# Generated by Django 6.0.7 on 2026-07-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_plantation', models.DateField()),
                ('stade', models.CharField(max_length=50)),
                ('kc', models.FloatField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.parcelle')),
            ],
        ),
    ]
