# Generated by Django 6.0.7 on 2026-07-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_culture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('vent', models.FloatField()),
                ('rayonnement', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('eto', models.FloatField()),
            ],
        ),
    ]
