# Generated by Django 6.0.7 on 2026-07-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_meteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.FloatField()),
                ('duree', models.FloatField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.parcelle')),
            ],
        ),
    ]
