# Generated by Django 6.0.7 on 2026-07-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0004_irrigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteo',
            name='eto',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etc', models.FloatField(default=0, editable=False)),
                ('besoin_eau', models.FloatField(default=0, editable=False)),
                ('volume_recommande', models.FloatField(default=0, editable=False)),
                ('irrigation_necessaire', models.BooleanField(default=False, editable=False)),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.culture')),
                ('meteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.meteo')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.parcelle')),
            ],
        ),
    ]
