# Generated by Django 5.1.3 on 2026-07-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "irrigation",
            "0005_alter_culture_id_alter_irrigation_id_alter_meteo_id_and_more",
        ),
        ("irrigation", "0005_alter_meteo_eto_recommandation"),
    ]

    operations = []
